# Generated by Django 2.2 on 2019-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default='', max_length=255)),
                ('preview_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('picture_url', models.CharField(max_length=400)),
                ('content', models.CharField(default='', max_length=255)),
                ('site_url', models.CharField(max_length=400)),
                ('vote_total', models.IntegerField(default=0)),
            ],
        ),
    ]
